# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/
#
# Copyright © 2019 BigBlueButton Inc. and by respective authors (see below).
#
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

source 'https://rubygems.org'

gem 'absolute_time', '~> 1.0'
gem 'aws-sdk-s3'
gem 'bbbevents', :git => 'https://github.com/mconf/bbb-events.git', :tag => '1.5.1'
gem 'builder', '~> 3.2'
gem 'docker-api'
gem 'dotenv'
gem 'elasticsearch', '<= 8.9.1'
gem 'fastimage', '~> 2.1'
gem 'i18n'
gem 'java_properties'
gem 'journald-logger', '~> 3.0'
gem 'jwt', '~> 2.2'
gem 'locale', '~> 2.1'
gem 'loofah', '~> 2.19.1'
gem 'mime-types'
gem 'nokogiri', '~> 1.13.10', '>= 1.13.10'
gem 'open4', '~> 1.3'
gem 'optimist'
gem 'rails', '~> 7.0'
gem 'rake', '>= 12.3', '<14'
gem 'rb-inotify', '~> 0.10'
gem 'redis', '~> 4.1'
gem 'resque', '~> 2.6', '>= 2.6.0'
gem 'retriable'
gem 'ruby-limiter'
gem 'rubyzip', '~> 2.0'
gem 'terminal-table'
gem 'tzinfo', '>= 1.2.10'
gem 'tz'
gem 'wisper'

group :test, optional: true do
  gem 'rubocop', '~> 1.34.0'
  gem 'minitest', '~> 5.14.1'
end
